name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      swift-versions: ${{ steps.set-matrix.outputs.swift-versions }}
    env:
      SWIFT_VERSIONS: |
        6.0.3
        6.1.0
    steps:
      - id: set-matrix
        run: |
          # Convert multi-line string to JSON array (jq is pre-installed on GitHub runners)
          VERSIONS=$(echo "$SWIFT_VERSIONS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "swift-versions=$VERSIONS" >> $GITHUB_OUTPUT

  test-macos:
    name: Test (macOS, Swift ${{ matrix.swift-version }})
    needs: setup
    strategy:
      matrix:
        swift-version: ${{ fromJson(needs.setup.outputs.swift-versions) }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

  test-ubuntu:
    name: Test (Ubuntu, Swift ${{ matrix.swift-version }})
    needs: setup
    strategy:
      matrix:
        swift-version: ${{ fromJson(needs.setup.outputs.swift-versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift-version }}

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

  test-windows:
    name: Test (Windows, Swift ${{ matrix.swift-version }})
    needs: setup
    strategy:
      matrix:
        swift-version: ${{ fromJson(needs.setup.outputs.swift-versions) }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        shell: powershell
        run: |
          # Enable Developer Mode
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"

          # Install Visual Studio dependencies
          winget install --id Microsoft.VisualStudio.2022.BuildTools --exact --silent --override "--wait --quiet --add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64"

          # Install Swift
          winget install --id Swift.Toolchain -e

          # Add Swift to PATH
          echo "$env:ProgramFiles\Swift\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
